CREATE DIRECTORY csvDir AS '/../Data/';

ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
userID VARCHAR2 (20),
NAME VARCHAR2 (50),
email VARCHAR2 (20),
PASSWORD VARCHAR2 (50),
date_of_birth DATE,
lastlogin TIMESTAMP,
)
)
LOCATION ('profile.csv')
)

ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
userID1 VARCHAR2 (20),
userID2 VARCHAR2 (20),
JDate DATE,
message VARCHAR2 (200),
)
)
LOCATION ('friends.csv')
)


ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
msgID VARCHAR2 (20),
fromID VARCHAR2 (20),
message VARCHAR2 (200),
toUserID VARCHAR2 (20),
toGroupID VARCHAR2 (20),
dateSent DATE
)
)
LOCATION ('messages.csv')
)

ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
msgID  VARCHAR2(20),
userID VARCHAR2(20),
)
)
LOCATION ('message_recipient.csv')
)

ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
gID         VARCHAR2(20),
name        VARCHAR2(50),
description VARCHAR2(200),
)
)
LOCATION ('groups.csv')
)

ORGANIZATION EXTERNAL (
TYPE ORACLE_LOADER
DEFAULT DIRECTORY csvDir
ACCESS PARAMETERS (
RECORDS DELIMITED BY NEWLINE
FIELDS TERMINATED BY ','
(
gID    VARCHAR2(20),
userID VARCHAR2(20),
role   VARCHAR2(20)
)
)
LOCATION ('group_membership.csv')
)
